graphhopper:
  datareader.file: ./texas-latest.osm.pbf
  graph.location: ./graph-cache

  graph.encoded_values: road_access, road_class, surface

  import.osm.ignored_highways: [motorway, motorway_link, trunk, trunk_link]

  custom_models.directory: ./custom_models

  profiles:
    - name: foot_fastest
      base: foot
      custom_model_files: [foot-fastest.json]

    - name: foot_balanced
      base: foot
      custom_model_files: [foot-balanced.json]

    - name: foot_cool
      base: foot
      custom_model_files: [foot-cool.json]

  profiles_ch:
    - profile: foot_fastest
    - profile: foot_balanced
    - profile: foot_cool
  profiles_lm: []

server:
  application_connectors:
    - type: http
      port: 8989
  admin_connectors:
    - type: http
      port: 8990
